### ISSUE TITLE
Support Diffie-Hellman

### ISSUE THREAD

**Issue by jyao1** [briansmith/ring#1038]
Is there any plan to support Diffie-Hellman (DH) key exchange algorithm in RING?

**Comment by Darkspirit** [comment]
According to best practices one should only use ECDHE. Can you migrate off DH? If not, why?

**Comment by jyao1** [comment]
The reason is quantum computing.
It is said that If quantum-computers became a reality, ECC-based algorithms (ECDH, ECDSA) could be broken easier than their same security level public key equivalents (DH, RSA / DSA). (https://blogs.cisco.com/security/cisco-next-generation-encryption-and-postquantum-cryptography, also https://en.wikipedia.org/wiki/Elliptic-curve_cryptography)

In some projects, we use RSA/DH, instead of ECDSA/ECDH.

**Comment by Darkspirit** [comment]
https://www.keylength.com/en/4/
Are you already using 7680 bit RSA & DHE instead of P-384 so that nothing of it can be decrypted in the far future?
Or do you even plan to use 15630 bit RSA & DHE instead of P-521/X448? At the moment, ring supports RSA 8192 bit at maximum.

https://blogs.cisco.com/security/cisco-next-generation-encryption-and-postquantum-cryptography
> DH/RSA/DSA vs ECDH/ECDSA: If quantum-computers became a reality, ECC-based algorithms (ECDH, ECDSA) could be broken easier than their same security level public key equivalents (DH, RSA / DSA). For example, 384-bit ECDH could be broken easier than 7680-bit DH. **But even though ECC would be broken by a quantum-computer, RSA would be broken as well, thus someone cannot claim that staying away from ECC offers significant advantage in a quantum-computer world**. ECC algorithms have significant performance advantages that should not be overlooked. Additionally, implementation of ECC algorithms can make a transition to post-quantum crypto easier. For example, implementing an ECDH step in a key exchange standard could relatively easily be adjusted to leverage a quantum-computer resistant key exchange algorithm instead of ECC.C.

Recent experiments use post quantum crypto on top of regular X25519:
https://blog.cloudflare.com/the-tls-post-quantum-experiment/
https://en.wikipedia.org/wiki/CECPQ2

**Comment by jyao1** [comment]
Thanks. I agree the RSA/DH would be also broken. It is about how many quantum bits are required.
People believe that ECC is an easier target for quantum computers than RSA/DH based upon the estimation, such as https://arxiv.org/abs/1706.06752.

So far, we are still using 3072bit RSA and DH. We may enlarge the key length in future or choose a new quantum safe algorithm directly according to NIST recommendation, such as https://csrc.nist.gov/Projects/Post-Quantum-Cryptography, https://csrc.nist.gov/news/2019/stateful-hbs-request-for-public-comments.
As such, we have no plan to migrate to ECDSA/ECDH because of above reason - ECC is an easier target for quantum computers.

That is why I am looking for the Rust based DH in RING. It will be great if RING can provide support for DH as well.

**Comment by saolof** [comment]
Having significant experience with this, ECDH is safer than DH for the same key size because implementing elliptic curve addition requires significantly more operations than modular multiplication, but the difference isn't huge. There is no real post-quantum benefit to DH. The reason why ECDH is less safe in practice is due to the smaller keys.

The work needed for a FTQC to compute the private key from the public key is effectively always the same as computing the public key from the private key. There is an extra quantum fourier transform step, but that's cheaper than squaring a number of the same size as the key using the naive quadratic multiplication algorithm.

Even then, the typical key size difference would buy you one extra year two at best once FTQCs start following Moore's law. If you want quantum resistance, use an actual post-quantum cryptography algorithm instead.
