### ISSUE TITLE
Ability to construct hmac::Algorithm

### ISSUE THREAD

**Issue by littledivy** [briansmith/ring#1216]
Hi :wave: 
I'm working on [Deno's WebCrypto implementation](https://github.com/denoland/deno/pull/9614). [Webcrypto allows](https://developer.mozilla.org/en-US/docs/Web/API/HmacKeyGenParams#properties) modifying length of the key, which is not possible since `hmac::Algorithm` digest field is private.

https://github.com/briansmith/ring/blob/1c36465f817f2e6697be917450cf1aded6d447ce/src/hmac.rs#L116

 Would you be interested in making this public? or are there other ways to do this? :slightly_smiling_face:  Thanks!

**Comment by briansmith** [comment]
> hash A DOMString representing the name of the digest function to use. You can pass any of SHA-1, SHA-256, SHA-384, or SHA-512 here.

Your project probably has a function that maps from strings to `&;static digest::Algorithm`. Instead, change that map to be from strings to `hmac::Algorithm` or `hkdf::Algorithm`. You can get the underlying `hmac::Algorithm` from the `hkdf::Algorithm` and you can get the underlying `digest::Algorithm` from an `hmac::Algorithm`. We do this in Rustls and it works great. Check out https://github.com/ctz/rustls/pull/457.

Alternatively, less ideally, you can easily write a function that returns an HMAC algorithm from a digest algorithm. Rustls use to do this before I refactored the code. Again, check out the above PR, this time looking at the old code, to see how to do it.

I intentionally make the `hmac::Algorithm` and `hkdf::Algorithm` types opaque because in the near future (or maybe even presently; I forget) there will be optimizations that rely on each `hmac::Algorithm` knowing more details about the digest algorithm than are available from a `digest::Algorithm`. So I don't intend to make an API to construct `hmac::Algorithm` from a `digest::Algorithm`.

**Comment by littledivy** [comment]
Yes, I directly map to `hmac::Algorithm` ([code](https://github.com/denoland/deno/blob/cd821f39b06bb5c3805496a147aa32060a9a7900/op_crates/crypto/key.rs#L67-L76)).

Here's a small example of my use case:
```rust
// Behaves as per WebCrypto HmacKeyGenParams. 
// https://developer.mozilla.org/en-US/docs/Web/API/HmacKeyGenParams#properties
fn generate_hmac(hash: String, length: Option<usize>) {
  let hmac_algorithm: ring::hmac::Algorithm = match hash { ... };
  // Ability to modify length (?)
  if let Some(length) = length {
    let mut alg = hmac_algorithm.digest_algorithm();
    alg.output_len = length;
    alg.chaining_len = length;
    hmac_algorithm = ring::hmac::Algorithm(alg);
  }
  // ...
  // generate key
}
```

Modifying the digest's `output_len` is what I'm looking for. Also, Thanks for the reply!

**Comment by briansmith** [comment]
Notice in the WebCrypto API documentation they recommend that the user uses the default length unless they have a good reason to use a different length. *ring*'s API encourages that too, by having the `generate` function always use the default length.

Currently, if you need to generate a key with a different length, then you need to use `ring::rand` to generate a slice of random bytes, and then use `hmac::Key::new` to construct the key from those random bytes.

If you'd like, you can submit a PR that adds a `generate_with_length` function to `hmac::Key` that accepts the length of the key.

**Comment by littledivy** [comment]
Opened #1218
