### ISSUE TITLE
feature request: Provide a wrapper around a Write/Read that computes the digest of everything written/read

### ISSUE THREAD

**Issue by danielzfranklin** [briansmith/ring#1255]
I want to write a bunch of things to a file and then write the digest of everything I've written. I thought it might be nice to have an API like so:

```rust
let mut file = File::open("foo.txt")?;
let mut out = WithDigest::new(&SHA256, &mut file);

for thingy in things_to_write {
    out.write_all(&thingy)?;
}

let digest = out.finish();
file.write_all(&digest)?;

file.flush()?
```

I wrote [a rough untested draft](https://gist.github.com/danielzfranklin/195c1344ebd83d0cad427013427aa180) of how this could be implemented. What would you think of a PR?

**Comment by briansmith** [comment]
@danielzfranklin Thanks for the suggestion. That is a very straightforward thing for somebody to write. Maybe in other circumstances it would even make sense to add to *ring*. But since that functionality can be built 100% on top of the public *ring* API and I have a huge backlog of things that really *must* be built into *ring*, I don't think it's reasonable for me to add that to the backlog. Thanks again for the suggestion though!
