### ISSUE TITLE
support for x86 cpus without mmx

### ISSUE THREAD

**Issue by goshhhy** [briansmith/ring#1303]
hi,

i'm trying to build code that uses rustls, and therefore _ring_, for some x86 processors without support for MMX. i can compile it, but when run and attempting to establish a connection, the program dies inside of the generated x86-mont-elf.S file due to it attempting to access an MMX register.

could feature detection be implemented for MMX in addition to the features that are already detected, falling back to the c implementation if it isnt available?

**Comment by briansmith** [comment]
> could feature detection be implemented for MMX in addition to the features that are already detected, falling back to the c implementation if it isnt available?

If somebody submits a PR that does this, I would help them get it accepted.

What is the Rust target triple that you use?

**Comment by goshhhy** [comment]
i486-linux, or i586-netbsdelf.

(the program in question doesn't work properly on i486 under netbsd, as it requires 8-byte atomics, and using libatomic causes issues. i'm running it on a 486 regardless, using an in-kernel emulator for cmpxchg8b that i wrote, to allow the executable to run properly).

**Comment by briansmith** [comment]
Most likely, one should try to fix this using some `#[cfg()]` logic to all the current i686 paths so that they are ignored on non-i686 targets. Then things should do the right thing for each algorithm, which would be to fall back to the plain Rust and/or plain C implementation (the same that is used for wasm32 and other targets that we don't have special support for).

I would take a PR to do that.

**Comment by briansmith** [comment]
Not sure if anybody wants this, but if they do:

Now we have generic implementations of every algorithm that wouldn't require SSE.

Look at how we have `STATIC_ARMCAPS` on ARM/Aarch64. If we did something similar for x86 for SSE2 so that i686 and x86_64 targets' feature detection for SSE2 was based on a compile-time constant indicating SSE2 is available, then there would be no performance cost to making the SSE2-based code conditional on that flag.

Hoewver, I'm closing this since it seems nobody is interested.
