### ISSUE TITLE
Consider to set the value of PRIVATE_KEY_PUBLIC_MODULUS_MAX_BITS instead of hard code 

### ISSUE THREAD

**Issue by zyj009148** [briansmith/ring#1429]
`const PRIVATE_KEY_PUBLIC_MODULUS_MAX_BITS: bits::BitLength = bits::BitLength::from_usize_bits(4096)`
This const now is 4096. But this size is not enough for my project, now I just hard code as 8192. Can we consider to make it as varable to pass to set the value?

**Comment by briansmith** [comment]
> `const PRIVATE_KEY_PUBLIC_MODULUS_MAX_BITS: bits::BitLength = bits::BitLength::from_usize_bits(4096)`
> This const now is 4096. But this size is not enough for my project, now I just hard code as 8192. Can we consider to make it as varable to pass to set the value?

I'd rather we change it to 8192, rather than let people configure it themselves. It is dangerous to change constants arbitrarily like this as we might start making assumptions at any time based on the value of the constant.

This constant is set to 4096 instead of 8192 because larger values require a LOT of stack space during private key operations.

**Comment by briansmith** [comment]
Closing as not planned. If anything, we'll bump the hard-coded value higher.
