### ISSUE TITLE
chore(cross compiling): automatically add environment variables

### ISSUE THREAD

**Issue by sdwoodbury** [briansmith/ring#1617]
Would it make sense to automatically export `TARGET_CC=$CC` and `TARGET_AR=$AR` if `TARGET_CC` and `TARGET_AR` aren't defined yet?

**Comment by briansmith** [comment]
@sdwoodbury I think such automation belongs in gcc-rs and not in *ring*'s build.rs. WDYT?

**Comment by sdwoodbury** [comment]
I’ve always used CC, AR, ect for cross compiling. It looks to me like TARGET_CC is a non standard environment variable. I wouldn’t expect gcc-rs to handle it.

**Comment by andrewtj** [comment]
@sdwoodbury the [cc crate looks for `TARGET_CC`](https://github.com/rust-lang/cc-rs#external-configuration-via-environment-variables). I can't put my finger on the docs at the minute but I believe the convention was adopted from cargo and rustc.

**Comment by briansmith** [comment]
When cross-compiling there needs to be a distinction between host and target toolchains. That's why I recommend people use `TARGET_CC` and friends, since they work for all cases. Try to never use `CC` and the like, if you can avoid it.

I think I'm going to close this since I think the automation is best done in gcc-rs if it is to be done at all, and because I want to focus on using more Rust code and less C code, as a means to improving the usability of the build system.
