### ISSUE TITLE
Build failed on riscv64gc-unknown-linux-gnu arch

### ISSUE THREAD

**Issue by LiveMediaTools** [briansmith/ring#1967]
My build is on github action:

https://github.com/harlancc/xiu/actions/runs/8047131550/job/21975774198

**Comment by mjovanc** [comment]
I have similar issue using. Compiles great on arm64 m3 chip, but not on GitHub Actions using "ubuntu-latest". I get:

```sh
warning: ring@0.17.8: error: UnknownOperatingSystem

error: failed to run custom build command for `ring v0.17.8`
```

![Screenshot 2024-03-13 at 12 53 50](https://github.com/briansmith/ring/assets/33717111/61db51ea-24f8-43e3-935d-0b2da1366d94)

**Comment by briansmith** [comment]
@LiveMediaTools's build log contains:
> panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:

The solution is to upgrade your dependencies to ones that are using *ring* 0.17.x.

@mjovanc It sounds like your issue is different from this one. 

I'm going to close this since the issue was due to trying to use *ring* 0.16 on a target for which we added support in 0.17.
