### ISSUE TITLE
Undefined behaviour in ctr32_encrypt_blocks

### ISSUE THREAD

**Issue by jasonyu1996** [briansmith/ring#2162]
Hi! It looks like this code in `ctr32_encrypt_blocks` has undefined behaviours.

https://github.com/briansmith/ring/blob/befdc87ac7cbca615ab5d68724f4355434d3a620/src/aead/aes/ffi.rs#L174-L202

I reproduced the same logic with the FFI replaced with unsafe Rust and MIRI reports undefined behaviours: https://play.rust-lang.org/?version=nightly&mode=release&edition=2021&gist=2b08f1fac9a144fee06c956f14ff598e

The issue is that `in_out` is borrowed twice, first as `&in_out` and  then as `&mut in_out` (through `in_out.as_mut_ptr()`). The latter invalidates anything derived from the former, including `input`.

**Comment by briansmith** [comment]
> The latter invalidates anything derived from the former, including input.

Could you provide a reference for this rule, other than Miri?

**Comment by briansmith** [comment]
> The latter invalidates anything derived from the former, including input.

I guess the line `let output: *mut [u8; BLOCK_LEN] = in_out.as_mut_ptr().cast();` could be moved to be ahead of where the `input` borrow happens.

However, IDK that it makes sense for `input` to be considered invalidated with the way the code is now, in part because `input` is a sub-borrow (terminology?) of `in_out`. I think this is a difference between "Tree Borrows," which is the actual model used by Rust, and "Stacked Borrows," which is what MIRI uses, right?

**Comment by briansmith** [comment]
I'll need to check whether `MIRIFLAGS=-Zmiri-tree-borrows` changes the result.

**Comment by briansmith** [comment]
PR #2164 addresses this.

**Comment by jasonyu1996** [comment]
Tree Borrows also considers this a UB. As for the reasoning behind this, we had better consult people working on those aliasing models. They might also be interested in seeing more cases to help refine the models.

**Comment by briansmith** [comment]
PR #2164 addressed this.

**Comment by briansmith** [comment]
See also PR #2198.

**Comment by briansmith** [comment]
See also PR #2204. Interestingly, the ChaCha20-Poly1305 code was already using the same workaround implemented in PR #2164 for AES-GCM. PR #2204 just makes AES-GCM and ChaCha20-Poly1305 use the same exact code for it.
