### ISSUE TITLE
Deal with RSA private keys with `p < q` better

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#220]
_ring_ requires that RSA private keys have `p > q`. This requirement isn't strictly necessary. We have the restriction because the optimization and side channel protection in `GFp_rsa_private_transform` requires it. But, we could change `rsa_new_end` so that normalizes the private key to the `p > q` form when `p < q` without adding a lot of complexity and probably risking any additional side-channel leakage during the recalculation.

If, for some reason, we do incur significant extra risk during the recalculation, such that it would be inappropriate for `RSAKeyPair::from_der` to do this itself, then we should provide the functionality in some other way: either a different method in `RSAKeyPair`, or with a separate command line tool or documentation for using a separate command-line tool.

**Comment by briansmith** [comment]
The documentation might want to cite http://crypto.stackexchange.com/questions/18084/in-rsa-why-does-p-have-to-be-bigger-than-q-where-n-p-times-q/22661#22661

**Comment by briansmith** [comment]
At least, when we reject a private key because p < q, which is probably legal according to the spec, but not supported by ring, we should return an indicator that the application can turn into an error message that users can use to look up documentation about the issue. This would be the very first use of any error indication in ring beyond success vs. failure, but I think more fine-grained errors during private key importing are warranted because we know people are frequently going to run into issues regarding this.

**Comment by briansmith** [comment]
Ideally, we should add test cases for the corner cases mentioned in https://crypto.stackexchange.com/a/22661, just in case we decide to do things more like BoringSSL/OpenSSL in the future.

**Comment by 46bit** [comment]
Hi. I'd like to start contributing to Ring and I like the look of this issue. :)

I have limited knowledge of Number Theory, side-channels and RSA. So a couple of questions:

* Normalising to `p > q` is mostly obviously done by taking 
  
  ```
  p_normalised = max(p, q)
  q_normalised = min(p, q)
  ```
  
  I have little familiarity with practical timing issues, but this would require branch-less implementation of `max` and `min`? Is there a straightforward mindset to apply here, or should I start by absorbing as much of the RSA codebase as possible rather than making changes?

* I see no search results for `rsa_new_end`. I presume you're referring to `GFp_rsa_new_end`?

**Comment by 46bit** [comment]
@briansmith: Howdy! I'd still love to contribute, but still need a bit of help with the above?

**Comment by briansmith** [comment]
> Hi. I'd like to start contributing to Ring and I like the look of this issue. :)

Awesome!

> Normalising to p > q is mostly obviously done by taking
> 
> p_normalised = max(p, q)
> q_normalised = min(p, q)

In an RSA private key there are also some precomputed values like `dmp1` == d mod (p - 1), `dmq1` == d mod (q - 1)`, and `iqmp` = 1/q mod p == q**-1 mod p. 

> I have little familiarity with practical timing issues, but this would require branch-less implementation of max and min? Is there a straightforward mindset to apply here, or should I start by absorbing as much of the RSA codebase as possible rather than making changes?

Thus, if you swap `p` and `q` you also have to recompute these values. As you noted, this has to be done in a side-channel-protected way, if we do it.

> I see no search results for rsa_new_end. I presume you're referring to GFp_rsa_new_end?

It was renamed in the interim, I believe.

I'd rather not add the extra code to normalize the values if we can avoid it. I doubt many people need it. I'd rather give people a script or something that does the conversion, perhaps also converting PEM to DER, and have them run the conversion script if they run into a key where p and q are swapped relative to what *ring* expects.

So, I think in this issue, we should concentrate on changing the return type of the function such that it can return a distinct error code for the case where p and q aren't in the “normal” form and a different error code for the case where there is some other problem (e.g. syntax error).

**Comment by 46bit** [comment]
That sounds excellent and is super helpful. I'll get to it!

**Comment by 46bit** [comment]
I agree that normalising the values is more work than is worth keeping here. I'll be working on this in the coming holiday weeks and hopefully other issues too :)

**Comment by briansmith** [comment]
Cool. I recommend that you subscribe to #360, since I'm moving the code for enforcing these things from C to Rust.

**Comment by 46bit** [comment]
Hi. Is this still relevant?

**Comment by lucab** [comment]
I unfortunately have to report that I'm hitting interoperability issues due to this additional ring requirement. In particular, I've seen so far a good number of private keys generated for client authentication on kubernetes clusters that have `p < q`. This makes ring and rustls unhappy and in turn means that the user can't authenticate to the cluster.

I've not tracked down where those keys are actually generated, but my gut feelings are pointing toward the `crypto/rsa` package directly provided by golang stdlib. The core logic should be [here](https://golang.org/src/crypto/rsa/rsa.go?s=7297:7387#L200), and I'm not seeing any sorting step on the primes that are generated. If that's the case, I fear you'll see more of those `p < q` keys in golang-related projects.

@briansmith is there any way you could reconsider previous comments, relaxing this requirement to accept such keys? I'm currently manually swapping bits in my own keys offline, but this unfortunately won't scale for library/client developers targeting a general public.

**Comment by briansmith** [comment]
The above comments were written when we were using the logic from OpenSSL modified to remove some timing side-channels. Now all the OpenSSL code relevant to this issue has been replaced with our own Rust code that implements our own logic, so the above comments might not be relevant any longer.

Check out https://github.com/briansmith/ring/blob/f66121467def0f49f3adba5176ea6d0f0147fe66/src/rsa/signing.rs and notice that we make use of the fact that q < p and that q**2 < n and similar. So we “just” have to rewrite that logic to stop assuming those things, without introducing timing side channels, and without reducing efficiency. I think it probably can be done.

**Comment by briansmith** [comment]
PR #604 attempts to address this.

**Comment by briansmith** [comment]
Fixed by PR #604.
