### ISSUE TITLE
Reuse `BN_BLINDING` multiple times in RSA signing

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#234]
Right now, we create a new temporary `BN_BLINDING` value before signing and then throw it away right after signing, never using it again. Instead, we should make use of the reuse facilities already built into `BN_BLINDING` by saving a pointer to the `BN_BLINDING` in the `RSAKeyPair`. It should be saved in a `Mutex` so that multiple threads can access the blinding safely.

**Comment by briansmith** [comment]
Extra testing is needed:

* [ ] export `BN_BLINDING_COUNTER` as an extern `GFp_BN_BLINDING_COUNTER`.
* [ ] Create a test that uses the same `BN_BLINDING` at least `GFp_BN_BLINDING_COUNTER` +1 times, to exercise all the code paths in blinding.c. This should be complete the test coverage of `bn_blinding_update`.
* [ ] Create a test that is similar to `test_agreement_suite_b_ecdh_generate`, where the `RAND` returns unusable values forever, to test the logic where the blinding gives up after a bunch of tries.
* [ ] Look at the coveralls report to make sure that everything in `BN_BLINDING` is now covered.

**Comment by ranweiler** [comment]
Hi there! I'd like to take on this work. I'm really excited to pitch in on this project!

FYI, `master` currently doesn't build due to an unused variable warning introduced [here](https://github.com/briansmith/ring/commit/690ca69a6b3fcd08486121f9f76cca543f9d1448#diff-638f0be9ed22a0ee436c8fd7cb3f29c0R55), in 690ca69a6b3fcd08486121f9f76cca543f9d1448. Without that definition, everything builds, tests pass. I'm not sure if its inclusion was an accident, or if it _will_ be used once your work in #247 lands, so I'll leave that to you (rather than fixing it), and just rebase once a fix lands in `master`.

**Comment by briansmith** [comment]
> Hi there! I'd like to take on this work. I'm really excited to pitch in on this project!

Awesome!

> FYI, master currently doesn't build due to an unused variable warning introduced here, in 690ca69. 

Thanks! I'll fix that now!

**Comment by briansmith** [comment]
>> FYI, master currently doesn't build due to an unused variable warning introduced here, in 690ca69.
> Thanks! I'll fix that now!

Fixed. Thanks again!

**Comment by briansmith** [comment]
Fixed with #258. Thanks again!
