### ISSUE TITLE
Use a return type better than `Result<(), ()>`

### ISSUE THREAD

**Issue by thejpster** [briansmith/ring#249]
Would it make the API cleaner if you defined your own Result, rather than repeatedly using the idiom Result&lt;T, ()&gt; everywhere? It might be me, but I think all those empty brackets hurt readability. Actually, I'd also prefer there to be a ring Error enum so the caller can work out exactly what went wrong, but that's more work obviously.

Happy to send a diff if you think it's a good idea.

**Comment by briansmith** [comment]
I have thought about adding something like:

```
type Result<R> = core::result::Result<R, ()>;
type BooleanResult = Result<()>;
const OK: BooleanResult = Ok(());
const ERR: BooleanResult = Err(());
```

Is this along the lines of what you're thinking of?

The thing that held me back from that was my uncertainty regarding whether users would understand it.

> Actually, I'd also prefer there to be a ring Error enum so the caller can work out exactly what went wrong, but that's more work obviously.

I am open to the idea of reporting more specific error information, but I'd like to see specific proposals for more specific error reporting that are based on end-user needs of the library. In part, the simplistic error reporting in *ring* is a reaction—perhaps an overreaction—to the huge amount of complexity in OpenSSL's error reporting. I already thought of one case where it would be useful to have more specic error reporting: https://github.com/briansmith/ring/issues/220#issuecomment-230123247.

**Comment by thejpster** [comment]
Yes, that sort of thing. Basically I was proposing to do what std::io does.
The Error enum can be small, but it might be useful to know that your
in_out buffer was too short as opposed to say, your nonce. And of course if
you want the current behavior, you can ignore the Err's parameter. It's
basically for debugging/logging.

**Comment by thejpster** [comment]
#250

**Comment by briansmith** [comment]
(Quotes are from the PR discussion.)

> . See https://doc.rust-lang.org/book/error-handling.html#the-result-type-alias-idiom. I think copying stable API idioms from the Rust standard library is to be considered A Good Thin

Yep, I don't think the need to look up the definition is a blocker to improvements here. You say the proposed way is easier to read and I say it's not a clear improvement. So, I think we need to look at other factors beyond readability.

> If the various API calls returned different types, consider how you would have to implement the sign_and_verify_rsa() doctest function would be in signature.rs.

Good point. In real-world code, we actually have to map the *ring* error (which is always `()` now, but that could very well change) to something else. We can see that in webpki and rustls:

* https://github.com/briansmith/webpki/blob/badcafbe4924ec90efa4fe42cc93e7ec7c32d05a/src/signed_data.rs#L143
* https://github.com/ctz/rustls/blob/8c94da8a5e52711d3b1f1ccfa6730e8fa3dfe700/src/server_hs.rs#L375

Now, I think in real-world code, we're mixing various libraries that each have their own error codes, right? So, we already have to use something like `map_err` pretty pervasively. I think your point is that having a single error type in *ring* would make such wrapping easier. That seems to be the case in rustls and webpki:

* https://github.com/ctz/rustls/blob/96cfd47d484eff57ba92549fc55c91cd4cfc1fa4/src/verify.rs#L144

But, what if webpki and *ring* were in the same crate? Then they would have the same error type. But, since they are in separate crates, they have separate error types. But, is being in the same crate or not really what should drive the decisions about how to design the error types? I don't think so.

Let's step back and look at the use cases that are driving the desire to change the error reporting. What specific parts of the *ring* API would benefit from returning specific error codes and what errors should those functions differentiate? Is there a way we can change the API to make better use of Rust's static typing so that users of the library don't need to deal with error codes? I think we can make decisions about how to design the types for reporting those errors after answering these questions.

Probably the most obvious candidate for differentiating errors is the private key loading. There are so many private key formats and there are so many things that could go wrong that it would be good if the caller got an answer to `RSAKeyPair::from_der` that answered "Was my private key not in the correct format? Was my private key cryptographically bad (e.g. `n`, `p`, `q` aren't consistent or too large or too small according to *ring*'s criteria)?

What about other areas?

**Comment by thejpster** [comment]
Perhaps a hierarchical approach is useful.

What if there was a master Error enum which looked like:

    use signature;
    use aead;
    enum Error {
        SignatureError(signature::Error),
        AEADError(aead::Error),
        ....
    }

This means the error definitions are close the modules that define/use them, but it also means there is a consistent error type.

If I was writing an application that used ring and webpki, I might then declare something like:

    enum CryptoError {
        RingError(ring::Error),
        PKIError(webpki::Error),
        ...
    }

With judicious use of the Into trait, one sort of error would map into a 'higher' sort of error relatively cleanly.

Bonus points for implementing fmt::Debug.

**Comment by thejpster** [comment]
Incidentally, I agree with your approach of analyse the error cases first, it's just I'm not sure I know your library well enough to answer that question.

**Comment by thejpster** [comment]
I've updated #250 by putting the Result and EmptyResult types into the top level, to avoid the err:: qualification. It might cause problems if your uses are calling `use rust::*`, but I think I prefer Result to RingResult or somesuch.

**Comment by briansmith** [comment]
I thought of one potential concrete benefit to using a distinct `ring::Error` type instead of `()`: If I understand correctly, users could implement `impl From<ring::Error> for <User's Error Type>` to have *ring* errors automatically translated into their own error type. However, it's not clear to me yet if or how much that would benefit people. Might be worth experimenting in webpki and/or rustls.

**Comment by thejpster** [comment]
>> With judicious use of the Into trait, one sort of error would map into a 'higher' sort of error relatively cleanly.

> If I understand correctly, users could implement impl From<ring::Error> for <User's Error Type>

Yes, that's what I was getting at. I haven't get gotten my head around the difference between Into and From.

**Comment by briansmith** [comment]
I prototyped an implementation of a subset of what @thejpster proposed at https://github.com/briansmith/ring/tree/error. I am curious what people think. @djc? @tarcieri? @ctz? @Ms2ger? If we're going to do this then we should do it sooner rather than later. Especially, I'd like to do it before the crates.io publishing if we're going to do something like this.

My idea is to create an error type, `ring::error::Unspecified`, which is a unit type. I also created `untrusted::EndOfInput` for the untrusted crate and a `From<EndOfInput>` implementation for `ring::error::Unspecified`. I also made `ring::error::Unspecified` implement `std::error::Error`. My understanding is that all these steps will help users of *ring* map *ring* errors to their own error types in whatever fashion they like, and that this will also be sufficient for them to use the various error handling helper crates that have been created (error_chain, et al.).

In the future, we might have some functions return more specific error information, maybe. If so, then we can have an Error trait that all *ring* errors implement:

```
mod error  {
    #[cfg(feature = "use_heap")]
    trait Error :  std::error::Error { }

    #[cfg(not(feature = "use_heap"))]
    trait Error { }

    impl Error for Unspecified { }
}

mod signature {
    #[derive(Clone, Copy, Debug, PartialEq)]
    enum Error {
        WeakPublicKey,
        InvalidSignatureForGivenKey,
        SyntacticallyInvalidSignature,
    }

    impl error::Error for VerificationError { }
}
```

Then users that want to abstract over all ring errors could do so using the ring::error::Error type. But, I actually doubt that such a type would be useful except when an application is being prototyped.

There's a specific reason that I don't want to use an `enum Error { Unspecified }` that might get extended later with more error codes. Some functions really can't safely return anything more than a binary result. `ring::constant_time::verify_slices_are_equal` is a good example. If we use an `Error` enum like you suggest, then the type system can't enforce that `verify_slices_are_equal` only returns a binary result and not a more nuanced (and unsafe) result. This is the case for quite a few other functions where side-channel differentiation of errors is a significant problem. To me, having the type system indicate the potential for such leakage is very important.

**Comment by djc** [comment]
Given the outlined constraints, your change on the branch makes a lot of sense to me. I think we should add a note to the documentation somewhere (but probably not on every function!) to explain that many errors are unspecified due to concerns about side channels.

**Comment by briansmith** [comment]
Pushed to master: https://github.com/briansmith/ring/commit/ac848e11c5deaf0771caa59cf3ba4eea10e8ba73

The documentation is here: https://briansmith.org/rustdoc/ring/error/struct.Unspecified.html. Let me know if you think it needs to be clearer regarding the motivation. (The motivation was in the origin commit linked to above too.)

**Comment by djc** [comment]
Ah, must have missed that. The documentation looks good to me!

**Comment by thejpster** [comment]
I second that.

Top effort everyone. Very good of you to take an interest in a left field
suggestion from a complete random! Thank you very much.

**Comment by briansmith** [comment]
Closing this. Let's open up a new PR if there's more improvements to make. Thanks for all the effort on this!
