### ISSUE TITLE
Rename RAND_bytes?

### ISSUE THREAD

**Issue by twittner** [briansmith/ring#275]
I wonder if the unmangled public extern function `ring::rand::RAND_bytes` should maybe be renamed? Otherwise linking both `ring` and `openssl` could easily lead to symbol conflicts and segmentation faults, e.g. if openssl's `SSL_CTX_new` runs into ring's `RAND_bytes`.

**Comment by briansmith** [comment]
There is actually only one caller of `RAND_bytes` now: `BN_rand`, which is used in bn_test.cc and by `BN_rand_range_ex`.

https://github.com/briansmith/ring/pull/254 will replace `BN_rand_range_ex` so that it does not use `BN_rand`.

Then only the tests will use `RAND_bytes`. The tests only use `RAND_bytes` in one place: `TestBN2BinPadded`. David Benjamin from Google rewrote almost all the test in bn_test.cc to avoid being random, but he didn't do that one yet. He agrees with me that we should rewrite that test. 

Then nothing will use `RAND_bytes` and it will be removed.

So, I don't think we need to rename it, because we can just do that other work instead. But, I would accept a PR to rename it if it is an urgent issue. The easiest thing to do would be to rename it `GFP_BN_rand`.

More generally, one cannot safely link OpenSSL, BoringSSL, LibreSSL, and/or *ring* together in the same program. Eventually we will probably change this in *ring* so that it can be safely used in an app that is using one of those other things. But, that will be easier to do after we finish more of the oxidation work and other simplification work that is in flight. It might be a while before it is done.

**Comment by twittner** [comment]
Thank you for your quick reply!

> Then nothing will use RAND_bytes and it will be removed.
>
> So, I don't think we need to rename it, because we can just do that other work instead.

Sounds very good.

> But, I would accept a PR to rename it if it is an urgent issue.

It is not urgent for me. I just ran into this problem and thought I should maybe ask about the name conflict. But I understand that things are in flux and this particular problem will eventually go away.

> More generally, one cannot safely link OpenSSL, BoringSSL, LibreSSL, and/or ring together in the same program. Eventually we will probably change this in ring so that it can be safely used in an app that is using one of those other things.

Maybe the README could mention this?

Thanks again for your explanation and for creating and maintaining this library!
