### ISSUE TITLE
Ensure there are no linking conflicts if OpenSSL/BoringSSL/LibreSSL are linked along with *ring*

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#297]
If we didn't do anything, then linking OpenSSL and _ring_ into the same executable would cause very bad things to happen, because each defines functions with the same names but with different signatures.

The main work to resolve this was done in https://github.com/briansmith/ring/pull/280. The remaining work is:
- [ ] Verify that there are no conflicting names.
- [ ] Write a tool that can verify that there are no conflicting names
- [ ] Run that tool as part of the build on CI.

**Comment by alexcrichton** [comment]
Hello! I've tracked [this bug report comment thread](https://github.com/alexcrichton/ssh2-rs/issues/17#issuecomment-246777782) back to this location, and I think I may be able to help out at least a little bit with the "verify there are no conflicting names" part.

The fault in that issue was tracked down to happening when *ring* was linked into the crate, and not happening when *ring* wasn't linked in. Looking at the list of exported symbols in *ring* I see ones like `BN_rand`, which conflict with OpenSSL's symbols as well. The linkage of both libraries there happened as ssh2 binding libssh2 uses OpenSSL, and then rusoto transitively requires *ring*, causing both OpenSSL and *ring* to show up in the same process.

cc @e-oz

**Comment by briansmith** [comment]
@alexcrichton Thanks! I think 3181c1287854ca97a08d1b2fc92be0789ccba5da fixes that specific issue.

**Comment by briansmith** [comment]
> Thanks! I think 3181c12 fixes that specific issue.

This fix is in *ring* 0.6.0, which I just published to crates.io.

**Comment by e-oz** [comment]
Segfault is fixed!!!
👯💃🕺🏿🍾🎉
Thank you very much, @briansmith, @alexcrichton !

**Comment by alexcrichton** [comment]
@briansmith one part that may help with "Write a tool that can verify that there are no conflicting names" above is that I detected this by statically linking OpenSSL in a project that also included the *ring* crate. That gave a bunch of linker errors, so that may be a good smoke test if you'd like to test that this works over time perhaps.

Thanks for the quick fix as well!

**Comment by briansmith** [comment]
Done, and tested in CI for most targets.
