### ISSUE TITLE
SRP protocol

### ISSUE THREAD

**Issue by est31** [briansmith/ring#304]
It would be cool to have support for the SRP authentication protocol ([RFC 2945](https://tools.ietf.org/html/rfc2945)) for password based logins. It can be used for key generation and is very similar to the non EC version of DHE.

An API where you pass the hash function and the groups would be great, but it could also come with the groups that [RFC 5054](https://tools.ietf.org/html/rfc5054) specified.

**Comment by briansmith** [comment]
Would you be using this for HomeKit or for something else?

**Comment by est31** [comment]
Probably HomeKit is one use case, but my interests are more around minetest: https://github.com/minetest/minetest (disclaimer: I am contributor for minetest). I even added SRP support to minetest in the first place ([link to the library](https://github.com/est31/csrp-gmp)), and I also could try implementation of this feature for ring, but I'm not familiar with the code base and I probably can't meet the high quality bar that ring has (constant time, etc).

**Comment by briansmith** [comment]
Closing this because it's obviously not been interesting enough for anybody to actually work on, and because it isn't clear that even want SRP. If we were going to have an effort to do everything HomeKit does, or to interoperate with something else really important, then we might reconsider this as part of that specific effort.

**Comment by est31** [comment]
Since I've opened this issue, the [SRP](https://crates.io/crates/srp) crate has been published, so I guess I'm okay with you wanting to close this.
