### ISSUE TITLE
Support bcrypt

### ISSUE THREAD

**Issue by Keats** [briansmith/ring#343]
I'm currently using rust-crypto for the bcrypt crate but it doesn't seem that maintained.

Is bcrypt support possible or not? 
There's a pure Rust implementation in rust-crypto so porting it in ring should not be hard

**Comment by briansmith** [comment]
> Is bcrypt support possible or not?
> There's a pure Rust implementation in rust-crypto so porting it in ring should not be hard

I don't expect to add bcrypt any time soon, but I am open to being convinced otherwise.

You might consider just copy/pasting the rust-crypto code you depend on directly into the bcrypt crate and maintain it all in that crate. All of the crypto code used within the bcrypt algorithm is specific to bcrypt, and no other algorithms would make use of the bcrypt code, so it is really a self-contained thing.

**Comment by Keats** [comment]
> I don't expect to add bcrypt any time soon, but I am open to being convinced otherwise.

Not planning to try to convince :) I wasn't sure if ring is planning to be the source for all crypto in Rust or not

**Comment by briansmith** [comment]
> I wasn't sure if ring is planning to be the source for all crypto in Rust or not

In the case of password hashing, it might come up as something for *ring* to do in the future, but generally people seem happy using algorithm-specific crates for it. There's standalone crates for scrypt (ring-pwhash) and Argon2 already, so I think it makes a lot of sense to have a standlone crate for bcrypt.

**Comment by Keats** [comment]
Thanks for the details!
