### ISSUE TITLE
Suspected RSA public operations performance regression

### ISSUE THREAD

**Issue by ctz** [briansmith/ring#431]
I've been taking periodic performance measurements of rustls in the past months, as I do development. I noticed that client performance is down at the last check.

approx date | ciphersuite / settings | speed
---|---|---
2016-09-04 | `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` <br> client, server-auth, full | 1333.04 handshake/s
2016-09-20 | `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` <br> client, server-auth, full | 1355.32 handshake/s
2016-09-27 | `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` <br> client, server-auth, full | 1293.55 handshake/s
2017-01-26 | `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` <br> client, server-auth, full | 332.12 handshake/s

The matching server measurements don't show the same degradation, and indeed valgrind --tool=callgrind shows that the difference is in the RSA public key operations during certification verification.

The same certificate chain is used in these tests: 

- 8192-bit RSA, root
- 3072-bit RSA, intermediate
- 2048-bit RSA, end-entity

**Comment by briansmith** [comment]
What is the value of the public exponent `e` for these public keys? We did optimize and simplify the code recently for the case where e has hamming weight 2 (e.g. e in {3, 65537}) at the cost, potentially, of worsened performance for keys with exponents with larger hamming weight.

Also, can you try your benchmarking with e40672e6dc2bb39754c77f068dda9e351b406f6f#diff-38a0ab4201513465814b409efc07988f reverted? I didn't measure a significant performance impact from that at the time I landed it, but maybe I messed up my own benchmarking.

Which microarchitecture are you using for the benchmark? Haswell? Broadwell? Skylake? This would potentially make a big difference.

**Comment by ctz** [comment]
> What is the value of the public exponent e for these public keys?

All 65537.

> Also, can you try your benchmarking with e40672e reverted?

Will try that next.

> Which microarchitecture are you using for the benchmark? 

Skylake.

**Comment by ctz** [comment]
> > Also, can you try your benchmarking with e40672e reverted?
> Will try that next.

Yup, that's the cause.

**Comment by briansmith** [comment]
> Yup, that's the cause.

Thanks!

I am reluctant to revert the change, because that is one of the last steps to a really important simplification of the bigint code.

Is there a real-world publicly-trusted 8192-bit root that you think is important to support? I have been thinking they're all 4096 or smaller. IIRC, the difference in speed for 4096-bit modulus and 8192-bit modulus with the new code is significant. Unless you have a real-world counterexample, I think we should only consider benchmarks that use 4096-bit, 3072-bit, and 2048-bit keys.

After the simplification work is finished, I think it would be straightforward to simply optimize the code for the new implementation to make it 2-4x as fast as it currently is, and I'm guessing that will be enough to recover whatever we've lost with this change.

WDYT?

**Comment by briansmith** [comment]
According to a censys.io search for "[current_valid_nss: true and parsed.subject_key_info.rsa_public_key.length: 8192 and parsed.extensions.basic_constraints.is_ca: true](https://censys.io/certificates?q=current_valid_nss%3A+true+and+parsed.subject_key_info.rsa_public_key.length%3A+8192+and+parsed.extensions.basic_constraints.is_ca%3A+true)", there are no NSS-trusted CA certificates with 8192-bit public keys.

**Comment by ctz** [comment]
Removing 8192-bit keys from the test produces these results:

approx date | ciphersuite / settings | speed
---|---|---
2016-09-27 | `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` <br> client, server-auth, full | 1891.04 handshake/s
2017-01-26 | `TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256` <br> client, server-auth, full | 691.39 handshake/s

(key sizes in the certificate chain are now 4096 -> 3072 -> 2048).

**Comment by briansmith** [comment]
Thanks for doing these measurements. I am planning to remove `GFp_BN_mod` and `GFp_BN_div` soon, which is the reason I made that change, so reverting that change is a last-resort option. I knew going into making the change that there was likely a potential for regression but I hadn't measured it being this bad. I suspect part of the reason is that I had done the measurement in BoringSSL, not in *ring*, and we don't have the GCC-/-Clang-only x86_64-optimized BIGNUM code.

Even still, because the new algorithm is just less efficient in terms of time, there's almost definitely going to be a not-insignificant regression. I guess we should think about what our goal is with respect to RSA verification performance. Up to this point, my goal has been to make EdDSA and ECDSA verification fast and to make RSA verification no slower than EdDSA & ECDSA.

**Comment by briansmith** [comment]
@avadacatavra, I saw your benchmarks in https://github.com/ctz/rustls/pull/47#issue-204641103. What version of *ring* were you using when you did them? Could you post some numbers here using the same configuration but with with *ring*'s commit e40672e reverted?

**Comment by avadacatavra** [comment]
@briansmith I'm using rustls 0.5.3, webpki 0.8.0 and ring 0.6.1

It looks like e40672e6dc2bb39754c77f068dda9e351b406f6f isn't in 0.6.1?

**Comment by briansmith** [comment]
> It looks like e40672e isn't in 0.6.1?

Right!: https://github.com/briansmith/ring/blob/9855c6bda6565e6e189b8a646ecfce1fec0ce929/crypto/bn/montgomery_inv.c

That means we still need to identify the problem(s).

**Comment by DemiMarie** [comment]
@briansmith Why is it so important to delete `GFp_BN_mod` and `GFp_BN_div`?

**Comment by DemiMarie** [comment]
@briansmith Does e40672e6dc2bb39754c77f068dda9e351b406f6f create a timing leak?

**Comment by briansmith** [comment]
@DemiMarie The old code, using `GFp_BN_mod`/`GFp_BN_div`, had a timing leak. The new code is the intermediate step to eliminating the timing leak.

The reason for eliminating `GFp_BN_mod`/`GFp_BN_div` are (1) Eliminate timing leaks, (2) make the code more clear in preparation for doing the formal proofs of correctness, and (3) reduce code size.

**Comment by briansmith** [comment]
See #453, which contains a draft of the thing I was talking about in my previous comment.

**Comment by briansmith** [comment]
See PR #659 which has a WIP solution for this. Unfortunately I don't have time to measure the performance improvement or what the optimal trade-off between shifts and exponent values should be. All feedback is appreciated.

**Comment by briansmith** [comment]
PR #659 merged, which brings back the performance to at least something close to what it was originally, without sacrificing the simplicity that we were aiming for. In particular, we didn't have to bring back long division/modulo arithmetic. Please file new issues with new benchmarks if the performance is still not sufficient.

**Comment by briansmith** [comment]
Also:

1. Thanks @ctz for letting me know about this in the first place.

2. RE: 

> I suspect part of the reason is that I had done the measurement in BoringSSL, not in ring, and we don't have the GCC-/-Clang-only x86_64-optimized BIGNUM code.

I had written the RSA benchmarking code in BoringSSL to measure the RSA Montgomery precomputation before I submitted the new shift-only algorithm's implementation to BoringSSL, specifically to ensure it didn't regress performance. The benchmark showed no performance change so we went ahead with the change in BoringSSL and in *ring*. That was over a year ago. Then two months ago we discovered that the benchmark code I submitted had a bug in it and it wasn't measuring the right thing at all; see https://boringssl.googlesource.com/boringssl/+/f11ea19043f2b3ee42e4a76d0645914347e1a36e. Once that bug was fixed, the BoringSSL benchmark started reflecting the regression reported here.

BoringSSL ended up reverting back to using `BN_mod`-since it is a little faster than the exponentiation-based algorithm; see https://boringssl.googlesource.com/boringssl/+/9af9b946d2b38c0310f409cc4a071c5f6978b0ae. However, in *ring* we're going with the exponentiation-based algorithm because I don't think the performance win from using `BN_mod` would be worth adding (the equivalent of) `BN_mod` back to *ring*.
