### ISSUE TITLE
Allow building just hash algorithms in some way

### ISSUE THREAD

**Issue by luser** [briansmith/ring#432]
I'd like to use a hash algorithm from ring but I don't need the rest of the crate currently. It would be nice if there was a way to do this, whether that's Cargo features or building the hash algorithms as a separate crate.

**Comment by Philipp91** [comment]
What is your use case / motivation? Faster compiling? Smaller binary size?

**Comment by luser** [comment]
Mostly faster compiling, yeah. Rust compilation is slow enough, pulling in another large dependency just to use one small bit of it makes the problem even worse.

**Comment by briansmith** [comment]
I appreciate the goal of improving the compilation speed, but I don't want to reduce the usability or maintainability of *ring* to do it in this way, at least without a profile of the build showing that there aren't less disruptive ways to improve the build.

Regardless, we'll be doing some thing to improve the compilation speed. For example, if you build from crates.io (or a mirror of it), the PerlAsm will soon be preprocessed into *.S files so that the Perl step can be skipped.
