### ISSUE TITLE
Add support for SHA224

### ISSUE THREAD

**Issue by Wilfred** [briansmith/ring#438]
Would it be possible to add support for SHA224? This would allow us to depend entirely on ring in the Remacs project.

**Comment by moosingin3space** [comment]
Seconding this, I'd like to be able to completely get rid of Emacs' private implementation of hash functions.

**Comment by briansmith** [comment]
Hi, I am happy to help you use *ring*. I'm a bit unsure what to do, because we intentionally don't support SHA-224 because nobody should be using SHA-224. We only support SHA-1 because of some the-internet-would-break-if-we-didn't things use it like Git and OCSP and TLS.

So, first, can you simply not implement SHA-224 in Remacs? Like, just pretend it doesn't exist? That seems ideal to me, not just as a *ring* contributor, but also as a crypto person in general.

**Comment by moosingin3space** [comment]
@Wilfred do you know what relies on SHA224?

**Comment by briansmith** [comment]
It seems like there's not a strong use case for adding this to *ring*. In the case of Remacs, you can simply use a pure Emacs Lisp implementation of SHA-224 because nothing performance- or security- critical should need to use it. That would already be required for MD5 anyway.
