### ISSUE TITLE
Speed up ARM release builds on travis

### ISSUE THREAD

**Issue by pietro** [briansmith/ring#481]
At the end of the travis build script we do a regular `cargo build` to test that building ring works. Unfortunately a lot of time that pushes the android release builds over the maximum time allowed for builds. We could remove that extra step at least for android.

**Comment by briansmith** [comment]
Definitely we need to do something to fix the timeouts. It might be better to identify which test(s) are taking a really long time and do something about them.

**Comment by pietro** [comment]
On debug builds:
```
test digest::tests::shavs::SHA1::monte_carlo_test ... test digest::tests::shavs::SHA1::monte_carlo_test has been running for over 60 seconds
test ec::x25519::tests::test_agreement_ecdh_x25519_rfc_iterated ... test ec::x25519::tests::test_agreement_ecdh_x25519_rfc_iterated has been running for over 60 seconds
```

On release builds:
```
test digest::tests::test_i_u_f_sha384 ... test digest::tests::test_i_u_f_sha384 has been running for over 60 seconds
test digest::tests::test_i_u_f_sha512 ... test digest::tests::test_i_u_f_sha512 has been running for over 60 seconds
test digest::tests::test_large_digest_sha1 ... test digest::tests::test_large_digest_sha1 has been running for over 60 seconds
test digest::tests::test_large_digest_sha256 ... test digest::tests::test_large_digest_sha256 has been running for over 60 seconds
test digest::tests::test_large_digest_sha384 ... test digest::tests::test_large_digest_sha384 has been running for over 60 seconds
test digest::tests::test_large_digest_sha512 ... test digest::tests::test_large_digest_sha512 has been running for over 60 seconds
```

More info on https://travis-ci.org/pietro/ring/builds/209505261

**Comment by briansmith** [comment]
I noticed that when the build script fails, e.g. because `cc1` cannot be found when building the C/asm code in build.rs, it takes 5 minutes before the error is reported by Travis CI. This indicates that it takes about 5 minutes before the build script even runs. We should try to find a way to eliminate that 5 minutes. Maybe the solution for that is to switch to Travis CI's Docker system.

We can also skip the `test_large_digest_sha1` test on Android ARMv7 targets. That test is testing the cross-platform logic. Ideally we'd keep the other `test_large_digest_sha`* tests intact unless/until the builds time out even when `test_large_digest_sha1` is disabled.

**Comment by briansmith** [comment]
> We can also skip the test_large_digest_sha1 test on Android ARMv7 targets. 

I did this in 3919cd7f1f2064b4b7c102b84b32531c754fde74. It seems to have cut the run time on Travis CI by at least 10 minutes!

**Comment by pietro** [comment]
I tried using docker on travis for the android builds but it fails because the filesystem of the container is too small for the android image. My guess is that most of those initial 5 minutes are eaten mostly by the creation of the android AVD.

**Comment by briansmith** [comment]
> At the end of the travis build script we do a regular `cargo build` to test that building ring works. Unfortunately a lot of time that pushes the android release builds over the maximum time allowed for builds. We could remove that extra step at least for android.

I removed the regular `cargo build` step in 0ec0e152a4af47466f7d4cdc934600d60f7fd9ca.

I also redid how the Travis CI integration works with the goal of getting to the `cargo test --no-run` step ASAP.

There is probably more work that can be done to improve the build times but I don't think this issue is useful anymore for tracking it, so I'm closing it. Thanks @pietro for all your work here and elsewhere!
