### ISSUE TITLE
Compiling ring 0.7.3 from crates.io with  CARGO_INCREMENTAL=1 RUSTFLAGS="-Zincremental-info" causes compiler warnings

### ISSUE THREAD

**Issue by weiznich** [briansmith/ring#493]
If I try to compile ring 0.7.3 from crates.io rustc will emit several [warnings](https://gist.github.com/weiznich/1eb9128fe23a4980235f4e18ed0a5db3) with the following message:
```
warning: Quasi-quoting might make incremental compilation very inefficient: NtExpr(..)
```
Expected:
Compiling ring from crates.io does not show any warning

Environment:
rustc 1.17.0-nightly (8c4f2c64c 2017-03-22)
export CARGO_INCREMENTAL=1 RUSTFLAGS="-Zincremental-info"

**Comment by briansmith** [comment]
Thanks for the bug report. Although what we're doing here is probably somewhat uncommon, I think this bug is a bug in rustc. AFAICT there's no reason that incremental compilation needs to be slow due to this. Also, there's no flag (AFAICT) to turn off the warning. Please file a bug against rustc and link to it here. Then we can see how to fix it (either here, or in rustc).

**Comment by weiznich** [comment]
I've filled already a bug report against rustc. [Diesel](https://github.com/diesel-rs/diesel/issues/824) suffers from the same issue

**Comment by briansmith** [comment]
I updated the summary. It seems like the build works fine on Nightly, without warnings, as long as you don't enable these non-default options?

**Comment by briansmith** [comment]
It looks like this will (eventually) be fixed in rustc. If this is an urgent problem then send me a private email and I'll consider looking into it further. Otherwise, let's wait for the free fix from rustc.
