### ISSUE TITLE
Expose rsa::padding::PKCS1?

### ISSUE THREAD

**Issue by Keats** [briansmith/ring#511]
I would like to do the following:

```rust
...
Algorithm::RS256 => sign_rsa(&signature::RSA_PKCS1_SHA256, key, signing_input),
Algorithm::RS384 => sign_rsa(&signature::RSA_PKCS1_SHA384, key, signing_input),
Algorithm::RS512 => sign_rsa(&signature::RSA_PKCS1_SHA512, key, signing_input),
...
```

where `sign_rsa` definition would be: `fn sign_rsa(alg: &rsa::padding::PKCS1, key: &[u8], signing_input: &str) -> Result<String> ` but the `PKCS1` is marked as private and not re-exported anywhere (afaik).
I can do another `match` in my `sign_rsa` instead of doing it there to avoid writing the type so it's not a big deal but I was wondering whether it would be ok to expose it.

**Comment by briansmith** [comment]
@Keats Thanks for the suggestion. I understand why people would want this, and also why people would want even to split out the digest algorithm too, so one could write `sign_rsa(key, &digest::SHA256, &signature::RSA_PKCS1, msg)`. However, the *ring* API is really intentionally designed to work basically the opposite of that way, because in general people shouldn't be mixing and matching algorithms like this.

I know this makes things like JWT less convenient to implement in the way that people commonly try to implement it. However, I would like to work with some JWT library developers to try to solve the problem a different way. If you look at the [webpki](https://github.com/briansmith/webpki) project you can see that it defines a set of wrappers around the `ring::signature::Algorithm`s in *ring*. The user of webpki then has to pass in an array of the algorithm wrappers it wants to (potentially) use. This is how webpki enables/disables various combinations of algorithms. If you follow this style in your JWT library, then you'll solve not only this problem, but also have a convenient way to enable/disable algorithm combinations in your library. WDYT?

**Comment by Keats** [comment]
In the case of JWT, combinations are kind of set in stone. This was more of a request for the internal code than the user facing one: https://github.com/Keats/rust-jwt/pull/23/files#diff-92706ffa42c53b037132b2e4c87f7eefR71

The commented lines are how I would like to use it but since the type is not public, I have to do https://github.com/Keats/rust-jwt/pull/23/files#diff-92706ffa42c53b037132b2e4c87f7eefR41

I don't think I could wrap this type as it's not public.

**Comment by briansmith** [comment]
@Keats Thanks for filing this. I'm leaning towards closing it because they way you want to do things is literally the way the *ring* API is trying to discourage RSA from being used. Your API is designed to be congruent with the JOSE specifications, but that approach is totally different than *ring*'s approach to API design, so we're bound to have some ugliness in the adaptation of one approach to the other.

In particular, although we don't (can't, and don't want to) prevent the same RSA key from being used for multiple algorithms (padding schemes and/or digest algorithms), we want to encourage people to use a key with only one padding scheme and only one digest algorithm, and also to know what padding scheme and what digest algorithm the key is intended to be used with at the time the key is loaded, instead of at the time the key is used for the actual signing.

So, even though your request isn't unreasonable, I'm going to close this because it's counter to the project's goals. Thanks for filing the issue, though!
