### ISSUE TITLE
Replace `error::Unspecified` with something just a little more useful

### ISSUE THREAD

**Issue by heartsucker** [briansmith/ring#529]
For example, if I do RSA signature verification, I'm not sure if the error was because of ASN.1 or because the signature was invalid, and this makes testing and debugging a lot more tedious. I'd suggest something like `error::Opaque(String)` where you just get some text with the explicit warning that matching against it is unsupported, but it contains text that helps developers when using `ring`.

Related: #384

**Comment by briansmith** [comment]
We won't return a `String` because `String` is a heap-allocated type. We can return an enum like #384 started to do.

**Comment by heartsucker** [comment]
Fair enough. I guess the end result I want is to be able to get at least a little more information about what went wrong.

**Comment by briansmith** [comment]
Before we get into the implementation details, it would be helpful to know which areas you want to see more specific error reporting in.

The thing that people mentioned before is "Did signature verification fail because the public key is invalid or because the signature is invalid." Presumably they also want to know "Why do you think the public key is invalid?" in that case.

Are there other use cases for more detailed error reporting?

On the master branch, we've fixed the "p < q" compatibility issue and we've also loosened one other strict check of RSA private keys, so I expect most RSA private key errors will mostly go away. However, I imagine people will still want some detailed error reporting for when private keys are rejected, especially since *ring* has (up to now, at least) been more strict than other implementations in loading keys.

Regarding the AEAD API, I think the API is hard to use and people are hoping error reporting will help tell them what they're doing wrongly. I suspect the answer there isn't more detailed error reporting though; I think we need to make the API easier to use, and I'd rather invest in improving the API before we do detailed error reporting for AEAD stuff.

> Is bringing in failure acceptable to help with generating the boilerplate?

Maybe. I did not like its predecessor, `error_chain`, at all, but `failure` is a big improvement on it. I am not sure it is lightweight enough yet though, and I would like to see failure 1.x released first.

I suggest as an implementation strategy that we create the first few `Error` types by hand manually and make sure that users' expectations regarding error reporting are being met while meeting the various performance-related goals (no heap allocation, etc.) and maintenance goals (we don't want error reporting to be brittle where we risk breaking some users if accidentally while improving *ring*).

I think signature verification (including public key validation) would be an excellent starting point since low risk, AFAICT; there are no secrets involved so we don't have to worry about creating side channels.

**Comment by jrozner** [comment]
The areas specifically I've been working with are the rng and hmac signing/verification but overall, I can imagine it being difficult to work with throughout the rest of the crate. Part of the issue I have with Unspecified, in general, is that I essentially need to go spelunking through the code to see what sorts of things can return an error and why to understand if the error being returned is expected, there is something exceptional happening, it's caused by bad data as input, misuse of the api, or some other problem. Until I've read through the code I don't know that I've handled all the error cases or even what I need to be concerned about with a specific api.

For instance, when attempting to fill a buffer with the rng with a nonce fill() returns Result<(), Unspecified> and it's unclear why or what could cause this to fail. Am I using the api wrong and somehow managed to get it to compile? Is there not enough entropy to fill the buffer? The documentation RLS provides in editor isn't overly helpful because it just provides the trait information and going to the rustdoc for ring::rand::SystemRandom doesn't explain what the failure cases of fill are either. I essentially need to track down the OS specific code to figure out what to do for correct error handling in my code.

I understand the fear of surfacing low level errors with more information and the ease at which incorrect use can lead to side channels and oracles. However, as a developer it made it much more difficult for me to get started building out my code, ensuring it was correct and that I handled the failure cases correctly, and was using the library correctly. I personally feel like it would be more useful to provide more clarity and additional documentation/examples explaining how/why side channels are dangerous, how they are introduced, and how to build a public api that avoids surfacing them.

**Comment by briansmith** [comment]
I did some work on this in 9968baa55dd595d3120c5290d03341b69b3e9bfa and 97d5877fbf8605d2c3aacb19c709a1ce40e672bc. Now when creating an RSA, ECDSA, or Ed25519 key pair object, if the key is rejected, an error that has a more useful `std::error::Error::description()` is returned.

It would be great if somebody could extend this work to the rest of the `ring::signature` API so that, for example, signature verification reports whether the signature verification failed because the public key was invalid, the signature is the wrong length, or some other reason (presumably, the signature is just wrong for that public key).
