### ISSUE TITLE
Reformat/re-indent all the source code with 2-space indents

### ISSUE THREAD

**Issue by briansmith** [briansmith/ring#543]
For various reasons, the *ring* source code needs to have line lengths of 81 characters or less. 4-space indents work quite poorly with an 80/81-character line length limit. I've experimented with using 2-space indents for Rust code in another code base and it seems to be better in that many fewer lines wrap at 80 characters, and discerning the indent levels with the smaller indent isn't problematic.

If you've contributed significant patches to *ring* and you disagree with this plan, please speak up.

**Comment by ranweiler** [comment]
I'm inclined _against_ doing this, but don't feel too strongly about it. I feel like we are much more impacted by (rightly) preferring qualified imports and often having long-ish method and foreign function names. So, my reflex is to doubt that this would help very much with some of the more awkward line wraps, relative to costs. I'd much rather bump the column limit, slightly (though I strongly prefer 80 chars).

In codebases I've worked on where we've done bulk reformats, it can make blaming annoying, though that is a nit. More importantly, when there are a lot of annotations and longer names like in *ring* (Rust generally?), I (unusually for me) prefer 4 spaces: the mere 2 space indent kind of gets lost in the shuffle, and doesn't feel sufficiently visually significant. It is kind of funny in Rust, because a partial statement like `let mut x = ` takes up 12 spaces. With 2 spaces, you could have 4 levels of indentation (starting at `let`) before you even get to the name being bound!

Of course, in many other settings, I personally prefer 2 spaces, and it is nice to have the Rust and C styles match, I suppose.

I guess I would counter-suggest: could we get a bigger improvement by changing how we split lines for function calls with many/verbose arguments?

Compare the following samples (with 80 `/`'s for reference):

## Existing
```rust
////////////////////////////////////////////////////////////////////////////////
    pub fn generate_pkcs8(rng: &rand::SecureRandom)
            -> Result<[u8; ED25519_PKCS8_V2_LEN], error::Unspecified> {
        let mut seed = [0u8; SEED_LEN];
        try!(rng.fill(&mut seed));
        let key_pair = Ed25519KeyPair::from_seed_(&seed);
        let mut bytes = [0; ED25519_PKCS8_V2_LEN];
        pkcs8::wrap_key(PKCS8_TEMPLATE, PKCS8_SEED_INDEX, &seed[..],
                        key_pair.public_key_bytes(), &mut bytes[..]);
        Ok(bytes)
    }
```

## 2-space indent
```rust
////////////////////////////////////////////////////////////////////////////////
  pub fn generate_pkcs8(rng: &rand::SecureRandom)
      -> Result<[u8; ED25519_PKCS8_V2_LEN], error::Unspecified> {
    let mut seed = [0u8; SEED_LEN];
    try!(rng.fill(&mut seed));
    let key_pair = Ed25519KeyPair::from_seed_(&seed);
    let mut bytes = [0; ED25519_PKCS8_V2_LEN];
    pkcs8::wrap_key(PKCS8_TEMPLATE, PKCS8_SEED_INDEX, &seed[..],
                    key_pair.public_key_bytes(), &mut bytes[..]);
    Ok(bytes)
  }
```

## 4-space indent, modified argument breaking
```rust
////////////////////////////////////////////////////////////////////////////////
    pub fn generate_pkcs8(rng: &rand::SecureRandom)
            -> Result<[u8; ED25519_PKCS8_V2_LEN], error::Unspecified> {
        let mut seed = [0u8; SEED_LEN];
        try!(rng.fill(&mut seed));
        let key_pair = Ed25519KeyPair::from_seed_(&seed);
        let mut bytes = [0; ED25519_PKCS8_V2_LEN];
        pkcs8::wrap_key(PKCS8_TEMPLATE, 
                        PKCS8_SEED_INDEX, 
                        &seed[..],
                        key_pair.public_key_bytes(), 
                        &mut bytes[..]);
        Ok(bytes)
    }
```

OTOH, It can be annoying to lose a bunch of vertical space, of course.

I think you should go ahead and do whatever you think is best, but maybe sit on it for a bit longer, and continue to audition it in lots of random, unrelated areas of the codebase.

**Comment by briansmith** [comment]
I don't see an advantage to the one-argument-per-line convention other than consistency with what I think was standardized as the rustfmt default. I do a lot of work on *ring* on a laptop (which is main "various reasons" above) so I'm quite adverse to wasting space. One good thing about *ring* is that we don't have many levels of nesting and so I don't think there's much to worry about in getting “lost.” OTOH, it might also then be the case that there's not much advantage to making this change.

**Comment by ranweiler** [comment]
> I don't see an advantage to the one-argument-per-line convention other than consistency with what I think was standardized as the rustfmt default.

Agreed.

> One good thing about *ring* is that we don't have many levels of nesting and so I don't think there's much to worry about in getting “lost.”

That's true. To me, that favors a 4-space indent: we have the freedom to embrace a larger indent that is visually significant relative to average identifier length, without blowing our column budget. But, that may have a low (or negative!) subjective value to you.

I'd vote to leave it at 4, but you have to read the *ring* code more than anyone else, so I think it's fair to optimize for that, if it feels worth it. It is really fine either way, imo.

**Comment by briansmith** [comment]
I'm going to close this w/ no action. At some point we should figure out a reasonable way to (automatically) format the *ring* code that makes it easy to review the code even on a regular-sized laptop screen, but this is not a high priority issue now.
