### ISSUE TITLE
Announce Mailing List

### ISSUE THREAD

**Issue by andrewtj** [briansmith/ring#614]
I've missed a release or two of *ring* over the past year or so even though I watch this repo and follow the crate on crates.io, and so I wondered if you'd consider setting up an announce mailing list to broadcast new releases and the like?

**Comment by jonas-schievink** [comment]
There are alternative solutions to this that don't require any work from the maintainer.

For example, GitHub has Atom feeds for releases, here's the feed for ring: https://github.com/briansmith/ring/releases.atom

Another alternative are email notifications from https://about.sibbell.com/

**Comment by briansmith** [comment]
When I help other projects integrate *ring* into their project, I usually directly manage all aspects of the *ring* integration, including the upgrades and things like that. Otherwise, outside of that, I don't want to spend time maintaining any official release notifications.

It seems to me that there must be some kind of tool that will watch crates.io and notify people of new versions of the crates they care about. I would love to use such a service myself.

Anyway, I am going to close this since it is unlikely I'm going to create a mailing list any time soon. Thanks for the very reasonable suggestion though!
