### ISSUE TITLE
Streaming API for AEADs

### ISSUE THREAD

**Issue by dabo8008** [briansmith/ring#704]
Maybe I do not understand the documentation correctly but I couldn't find what I was looking for.
I'm looking for encrypting large data with AES_GCM. Normaly I would read (from a file or socket or something) and write (to a file, socket, etc.) in chunks. Is this not possible? Do I have to read the whole content into the memory and then encrypt or decrypt it in memory?

**Comment by briansmith** [comment]
> Maybe I do not understand the documentation correctly but I couldn't find what I was looking for.
> I'm looking for encrypting large data with AES_GCM. Normaly I would read (from a file or socket or something) and write (to a file, socket, etc.) in chunks. Is this not possible? Do I have to read the whole content into the memory and then encrypt or decrypt it in memory?

It's usually not a good idea to use AES-GCM and similar AEAD mechanisms on large inputs. They are only safe to use if the tag is generated/validated before the ciphertext/plaintext is written/read. That is, in general streaming APIs for such AEADs are not safe. That's why we don't expose a streaming API.

Usually a mechanism for using such AEAD algorithms will define a way to chink the input into multiple small blocks, each of which is encrypted & authenticated. This block size is designed to be small enough so that an in-memory buffer holding a whole block is reasonable.

If that kind of scheme doesn't work for what you're doing, I'd like to learn more about the specifics of your use case to see if it is something worth adding special, less safe, support for. In particular, is this needed for some standardized algorithm?

**Comment by briansmith** [comment]
I'm going to close this based on the discussion above. If you need this functionality and can't discuss your need publicly, feel free to email me: brian@briansmith.org.

**Comment by sam0x17** [comment]
We use variable size blocks of 8 MB to 128 MB blocks, but for UI purposes (e.g. showing a smooth progress bar vs having it jump every time a block is processed) and so we can avoid using a large amount of memory at any given, we require a streaming API. Please consider adding support for this.
