### ISSUE TITLE
Make 'signature::KeyPair::public_key' a public function

### ISSUE THREAD

**Issue by manifest** [briansmith/ring#741]
In the docs [key_pair.public_key().as_ref()](https://github.com/briansmith/ring/blob/8b9d45c53ce9ed984a573bfa88e4cc28b09b587b/src/signature.rs#L153) is used as public function, but implemented as a [private](https://github.com/briansmith/ring/blob/8b9d45c53ce9ed984a573bfa88e4cc28b09b587b/src/ec/suite_b/ecdsa/signing.rs#L231).

**Comment by briansmith** [comment]
It's already public because it is a trait method. Note that rustc will give you a confusing error message if you don't `use ring::signature::KeyPair;` in the module that you're trying to use it in, indicating that `public_key` is private. These types each have a private `public_key` field, and rustc is trying to be helpful by giving you a hint, but unfortunately its hint is the wrong one.

So, try adding `use ring::signature::KeyPair;` to the module you're having trouble in.

Note that the doc tests pass on my machine, as-is.

**Comment by briansmith** [comment]
For reference, here is the error message I get when I remove the `use ring::signature::KeyPair` from the doctest:

```
---- src\signature.rs - signature (line 129) stdout ----
error[E0599]: no method named `public_key` found for type `ring::signature::KeyPair` in the current scope
  --> src\signature.rs:153:38
   |
26 | let peer_public_key_bytes = key_pair.public_key().as_ref();
   |                                      ^^^^^^^^^^ private field, not a method
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
3  | use ring::signature::KeyPair;
   |
```

**Comment by manifest** [comment]
Yes, my fault. Thanks a lot 👍
