### ISSUE TITLE
Question: Can I store a nonce in the aad?

### ISSUE THREAD

**Issue by jamessewell** [briansmith/ring#858]
Hi,

I've been working with `ring::{pbkdf2, aead}` to encrypt small, single UDP packet multicasts.

To get the nonce from client -> server it looks like I have two options:

- put it in the `aad` region (which I can't work out how to access pre-`open_in_place`)
- add it to the start of the transmitted `[u8]`

Bonus question: should the nonce be random in this case?

Cheers,
James

**Comment by jamessewell** [comment]
OK seems I massively understood the purpose of the `aad` region.

I now *think* it's for storing out of band data which you want to authenticate? So you'd need the same data at `open` as you used at `seal`?

Is this right?

**Comment by brycx** [comment]
> I now think it's for storing out of band data which you want to authenticate? So you'd need the same data at open as you used at seal?
>
>Is this right?

Yes, this is correct. `aad` is data that is authenticated, but not encrypted, along with the ciphertext on `seal_in_place`. Typically `aad` can be used for headers, version numbers, etc. In terms of ChaCha20-Poly1305 (I'm not too familiar with AES-GCM), the nonce is already authenticated because it is used to create the one-time-key that authenticates both the `aad` and ciphertext.

> put it in the aad region (which I can't work out how to access pre-open_in_place)

The `aad` is only authenticated and not a part of the output on `seal_in_place`.

> Bonus question: should the nonce be random in this case?

It's not safe to generate random nonces for each sealing operation using AES(128/256)-GCM or ChaCha20-Poly1305. For that you will want to look at a construction that supports larger nonces, such as XChaCha20-Poly1305. A monotonically increasing counter would be fine in this case. Just as long as a given nonce is never reused with a secret key.

I suggest taking a look at the [libsodium docs](https://download.libsodium.org/doc/secret-key_cryptography/aead) if you are unfamiliar with the constructions.

**Comment by jamessewell** [comment]
Thanks! That makes sense.

In the case of an increasing counter how would people normally deal with
service restarts? I’m guessing you can’t just start from 0 again?

In the same way if I have an unknown amount of nodes using a key do I need
to ensure that no two nodes share nonces?

Once again thanks for the help - there is s lot of conflicting info out
there on this stuff.

**Comment by briansmith** [comment]
Hi, I'm closing this because this is really a general discussion about AEADs and nothing specific to *ring*. Please reach out privately by emailing brian@briansmith.org if you need such assistance.

**Comment by jamessewell** [comment]
Thanks for the help regardless!
