### ISSUE TITLE
Asymmetric encryption with RSA

### ISSUE THREAD

**Issue by noneuclideangirl** [briansmith/ring#864]
I had a quick look at the issues here and the documentation, and it seems like `ring` supports RSA signatures but not actual encryption. Considering that `ring` doesn't have block ciphers either, is encryption simply not part of what `ring` is meant to do? Would this be a feature that could be considered in the future?

**Comment by josephlr** [comment]
Ring generally has APIs to cryptographic constructions which are useful and secure. It generally does _not_ expose the building blocks for these constructions. 

For example, ring exposes symmetric encryption though the [`aead` module](https://docs.rs/ring/0.14.6/ring/aead/index.html), instead of allowing users to use the block ciphers directly (which could lead to insecure usage). Similarly, it exposes APIs for RSA [singing](https://docs.rs/ring/0.14.6/ring/signature/struct.RsaKeyPair.html) and [verification](https://docs.rs/ring/0.14.6/ring/signature/struct.RsaParameters.html), instead of exposing raw RSA operations.

So direct asymmetric encryption would be less likely to be added than just adding RSA support to the [`agreement` module](https://docs.rs/ring/0.14.6/ring/agreement/index.html), for example. Would that help your use case?

**Comment by noneuclideangirl** [comment]
Thanks for the comment, very helpful!

The `aead` module addresses my use case, but not in the way I expected. The issue is that I need to allow the following:

1. Connection is established with an agreed key
2. Client sends encrypted file to server (who cannot read the file)
3. Connection closes
4. Connection is established with a different agreed key
5. Server sends encrypted file to client
6. Client decrypts the file

So by storing (e.g.) an AES key and using `aead`, I can achieve the task. Cheers!
