### ISSUE TITLE
AES-256-GCM 128 bit IV?

### ISSUE THREAD

**Issue by lf94** [briansmith/ring#896]
Hey!

I'm trying to mimic what subtle.crypto does in the browser. So far I think I'm very close, but I'm stuck up on this IV issue. It appears ring only supports 96 bit IVs / nonce... But then I read somewhere else that 128 bit IV is actually a nonce plus a counter. I also read a special calculation has to happen when its 128 bits. I don't know what to believe. The NIST document says 96 bits is the standard.

Here is my code.

```rust
extern crate ring;
extern crate base64;

use std::num::NonZeroU32;

fn main() {
  let data_base64 = "xBlzUAObL+5s5XjVWdRQYECDIZ8y0co=";
  let iv_base64 = "Pd3bIcERVs5qmLaQ3YApyw==";
  let salt_base64 = "38zBHkqlTGy4pa1Y7WF+2cdeG1JCBSf70xLYazDvFiQ=";
  let password = "hello".as_bytes();

  let salt = &base64::decode(salt_base64).unwrap();
  let mut derived_key = [0u8; 32];

  ring::pbkdf2::derive(
    ring::pbkdf2::PBKDF2_HMAC_SHA256,
    NonZeroU32::new(10000u32).unwrap(),
    salt,
    password,
    &mut derived_key
  );

  println!("{:?}", derived_key);

  let nonce_and_counter = &base64::decode(iv_base64).unwrap();
  let nonce = ring::aead::Nonce::try_assume_unique_for_key(
    &nonce_and_counter[..12]
  )
  .unwrap();

  let mut ciphertext_vec = base64::decode(data_base64).unwrap();
  println!("{:?}", ciphertext_vec);

  let ciphertext_buf = ciphertext_vec.as_mut_slice();

  let unbound_key = ring::aead::UnboundKey::new(
    &ring::aead::AES_256_GCM,
    &derived_key
  )
  .unwrap();

  let nonce_sequence = OneNonceSequence::new(nonce);
  let mut bound_key: ring::aead::OpeningKey<OneNonceSequence> =
    ring::aead::BoundKey::<OneNonceSequence>::new(
      unbound_key,
      nonce_sequence
    );

  let result = bound_key.open_within(
    ring::aead::Aad::empty(),
    ciphertext_buf,
    0..
  );

  println!("{:?}", result);
}

struct OneNonceSequence(Option<ring::aead::Nonce>);

impl OneNonceSequence {
  /// Constructs the sequence allowing `advance()` to be called
  /// `allowed_invocations` times.
  fn new(nonce: ring::aead::Nonce) -> Self {
    Self(Some(nonce))
  }
}

impl ring::aead::NonceSequence for OneNonceSequence {
  fn advance(&mut self) -> Result<ring::aead::Nonce, ring::error::Unspecified> {
    self.0.take().ok_or(ring::error::Unspecified)
  }
}
```

It should decode to `{ a: 1 }`.

Note: My knowledge of cryptography is broad but not deep - please go easy :slightly_smiling_face:

**Comment by lf94** [comment]
I was able to do this successfully with the openssl crate - turns out that's what browsers are using to accomplish this anyway. I will close the issue since `ring` has particular design restrictions.

**Comment by josephlr** [comment]
> I'm trying to mimic what subtle.crypto does in the browser.

*ring* generally is a high-level cryptographic library. Contrast this with OpenSSL/BoringSSL have both high-level and low-level components. [`self.crypto.subtle`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) is lower-level than *ring*, so not all functionality will be mimic-able.

> So far I think I'm very close, but I'm stuck up on this IV issue.

First off, you want to be using 96-bit nonces with [AES-GCM](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/encrypt#AES-GCM). In subtle.crypto, this is passed in via an [`AesGcmParams`](https://developer.mozilla.org/en-US/docs/Web/API/AesGcmParams), where the docs mention that a 96-bit (12 byte) nonce should be used.

Most of *ring*'s complexity around nonces are to assure they are not used more than once. Reusing a nonce/key pair with AES-GCM is very bad (essentially breaking your crypto). 

> But then I read somewhere else that 128 bit IV is actually a nonce plus a counter.

So this confusion is probably caused by a confusion between AES-GCM's API and it's implementation.

Crypto details ahead:

The AES-GCM API always takes in a 96-bit nonce. Under the hood, GCM extends this nonce with a 32-bit *internal* counter. This gives us a 128-bits IV (AES is the underlying block cipher and it always uses  128 bit IVs regardless of mode/key size). AES-GCM then increments this *internal* counter for each block it encrypts (you don't have to do anything). 

However, we have to make sure this counter does not overflow, which *ring* checks for you, using more than `2^39` bytes in a single call to [`seal_in_place_separate_tag`](https://docs.rs/ring/0.16.8/ring/aead/struct.SealingKey.html#method.seal_in_place_separate_tag) will result in an error (see [the calculation here](https://docs.rs/ring/0.16.8/src/ring/aead.rs.html#689)).

> Note: My knowledge of cryptography is broad but not deep - please go easy

No problem! This stuff can be tricky. Let me know if you have questions about my explanation.
