### ISSUE TITLE
Uniform random integers in specific range

### ISSUE THREAD

**Issue by jpgoldberg** [briansmith/ring#942]
For a number of purposes, it is useful to get uniformly distributed random integers less than a give value. For example, one might to pick get a number in the range [0, 26). The following properties should be considered

1. Cryptographically secure
2. Uniform distribution (must avoid the modulo bias). (Yes, this actually follows from (1)
3. Not call the underlying RNG more than necessary (naive algorithm can be very wasteful)
4. Avoid integer divisions to reduce scope of timing attacks.

Note that the argument to the function is not expected to be kept secret.

**Comment by peteroupc** [comment]
In general, a method to [convert random bits to random integers](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomfunc.md#RNDINT_Random_Integers_in_0_N) in a range can be _either_ "constant-time" _or_ unbiased, but not both, unless the upper bound of the range is a power of 2.

I am aware of two relevant work efforts on generating a random integer from random bits:

- `cfrg/draft-irtf-cfrg-hash-to-curve`, which is a Crypto Forum Research Group draft that specifies a `hash_to_base` method that hashes an arbitrary string of bits into a finite field element (which is similar to the problem you describe in your issue).  See section 5.1 of the draft for security considerations relevant to this issue.  However, `hash_to_base` appears to be [designed to generate integers in huge ranges](https://github.com/cfrg/draft-irtf-cfrg-hash-to-curve/issues/194).   Moreover, the function appears to be in active development as of now; for example, see issue 202 of the `cfrg/draft-irtf-cfrg-hash-to-curve` repository.
- D. Lemire (@lemire) presented a multiply-then-shift strategy, which is a [fast alternative to the modulo reduction](https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/), for reducing a huge random number to an integer within a range.

**Comment by jpgoldberg** [comment]
It can’t be constant time in a literal sense, but its variation in time does not need to reveal any information about the secret.

**Comment by lemire** [comment]
> Avoid integer divisions to reduce scope of timing attacks.
>  (...)
> It can’t be constant time in a literal sense, but its variation in time does not need to reveal any information about the secret.

Can you elaborate on how you combine these two statements?

Division instructions often reveal something about their inputs in that their running times vary based on the input. (Of course, this depends on the hardware.)

But if you are forgoing "constant time" does that mean that you are fine with the revealing something about the inputs?

**Comment by ctz** [comment]
> In general, a method to [convert random bits to random integers](https://github.com/peteroupc/peteroupc.github.io/blob/master/randomfunc.md#RNDINT_Random_Integers_in_0_N) in a range can be _either_ "constant-time" _or_ unbiased, but not both, unless the upper bound of the range is a power of 2.

This is correct, but the key observation is that if the source of random bits in rejection sampling is a good quality RNG then the number of rejected samples (hence: the timing side channel) reveals nothing about the finally selected value.

If you wanted to model this, you'd give your adversary both the bound, the sequence of rejected bitstrings, and an RNG oracle and have them guess the final value.

hash-to-curve is a different problem, because the randomness source itself is sensitive key material -- performing rejection sampling on it leaks its value via the timing side channel.

**Comment by jpgoldberg** [comment]
> This is correct, but the key observation is that if the source of random bits in rejection sampling is a good quality RNG then the number of rejected samples (hence: the timing side channel) reveals nothing about the finally selected value.

Thank you. That is what I meant. 

Please note that I said "reduce scope of timing attacks". I did not say that the whole operation should be constant time. The number of rejected samples reveals information about the sought after range, but I also said that that information is not secret.

**Comment by briansmith** [comment]
I have a draft implementation of this:

0. Require the modulus `n`
1. Build a mask `m` from the leading zeros of the modulus `a: T`.
2. Generate a random value of type `T` using `ring::rand`.
3. Mask the generated value using `m`. Now the random value is guaranteed to be less than `2*n`.
4. If the random value is less than `n` return it. Otherwise, loop back to step 2.
