### ISSUE TITLE
Add git tags for releases

### ISSUE THREAD

**Issue by alex** [briansmith/ring#951]
It seems there hasn't been a tag in the last year or so.

**Comment by briansmith** [comment]
I stopped doing the tags because there's no guarantee that what GitHub claims to be version X is actually what is in the version X on crates.io. Therefore, it's potentially very misleading if they get out of sync. The published crate itself should contain the commit hash of the commit it was built from.

**Comment by alex** [comment]
Truly there is no such guarantee :-( Thanks.
